name: Upload Website to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    # match to your version of NodeJS
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.20.2

      # - name: Navigate to repo
      #   run: |
      #     cd $GITHUB_WORKSPACE

      - name: Install Dependencies
        run: |
          npm ci

      # use your greenwood build script
      - name: Run Build
        run: |
          npm run build

      - name: Deploy to S3
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2"
          FROM_PATH: "./public"
          # your target s3 bucket name goes here
          DEST_PATH: ${{ secrets.AWS_BUCKET_NAME }}